[[redirects]]
  from = "https://ludantis.netlify.app/*"
  to = "https://ludantis.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://io.ludantis.com/*"
  to = "https://seal-app-7l7eh.ondigitalocean.app/:splat"
  status = 200
  force = true
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"   
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"